[app]
url = "https://beta.lightandsound.design"
db = "db.sqlite"

[net]
http_addr = "[::]:80"
https_addr = "[::]:443"

[acme]
domain = "beta.lightandsound.design"
email = "studio249@foltz.io"
dir = "acme"
prod = true

[email]
smtp_addr = "smtp://localhost:1025"
from = "WLSD <studio@lightandsoun.design>"
